In [ ]:
import numpy as np  #does mathematical operation
import matplotlib.pyplot as plt #For plotting the graphs
import pandas as pd #making the data frames and import the csv files
import math
from sklearn import metrics

#from google.colab import drive #to import the google drive data

#drive.mount('/content/drive')   # to mount the drive data into the colab cloud and enter the activation code


In [ ]:
#cd /content/drive/"My Drive/Colab Notebooks/Linear_Regression" 


In [ ]:
#Taking the Dataset from URL and read it as CSV File
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
Colnames = ['sepal_length','sepal_width','petal_length','petal_width','Class']
dataset = pd.read_csv(url,names=Colnames)
dataset.head()      #to Read top 5 Values   

sepal_length  sepal_width  petal_length  petal_width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
dataset.tail()      #TO read last 5 Values

sepal_length  sepal_width  petal_length  petal_width           Class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
dataset.shape

(150, 5)

In [ ]:
training_dataset = dataset.values[:,0:4]

In [ ]:
training_dataset
training_dataset.shape

(150, 4)

In [ ]:
training_class_dataset = dataset.values[:,-1]

In [ ]:
training_class_dataset
training_class_dataset.shape

(150,)

In [ ]:
#To find the euclidiean distance between the points
def euclidiean_distance(row1,row2):     #Taking 2 observations as the parameters to find the distance between them
    distance = 0.0  
    for i in range(len(row1)):
        distance+=(row1[i]-row2[i])**2
    
    return math.sqrt(distance)

In [ ]:
#To find the unique classes from the dataser
unique_list = []
for x in training_class_dataset:
    if x not in unique_list:
        unique_list.append(x)
print(unique_list)

#to replcae the class with  numerical value
for i in range(len(training_class_dataset)):
    for k in range(len(unique_list)):
        if(training_class_dataset[i]==unique_list[k]):
            training_class_dataset[i]=k
            break
print(training_class_dataset)


['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
distance = []
for i in range(len(training_dataset)):
    distance.append([euclidiean_distance(training_dataset[i],training_dataset[52]),training_class_dataset[i]])
print(distance)
print(len(distance))

[[4.164132562731403, 0], [4.236744032862973, 0], [4.415880433163924, 0], [4.305810028322198, 0], [4.219004621945798, 0], [3.786819245752298, 0], [4.366921112179611, 0], [4.117037770047781, 0], [4.497777228809804, 0], [4.1856899072912706, 0], [3.9824615503479754, 0], [4.132795663954366, 0], [4.316248370981448, 0], [4.813522618623497, 0], [4.171330722922843, 0], [3.9874804074753776, 0], [4.130375285612677, 0], [4.134005321718878, 0], [3.6891733491393435, 0], [4.090232267243512, 0], [3.7775653535048206, 0], [4.045985664828782, 0], [4.737087712930806, 0], [3.8105117766515306, 0], [3.897435053981016, 0], [4.024922359499622, 0], [3.9749213828703587, 0], [4.037325847637271, 0], [4.113392760240627, 0], [4.174925149029621, 0], [4.12189276910499, 0], [3.8871583451153624, 0], [4.172529209005013, 0], [4.136423575989288, 0], [4.1856899072912706, 0], [4.358898943540674, 0], [4.095119045888655, 0], [4.1856899072912706, 0], [4.572745346069471, 0], [4.0718546143004675, 0], [4.262628297189424, 0], [4.56

In [ ]:
distance.sort()
distance

[[0.0, 1],
 [0.26457513110645914, 1],
 [0.2828427124746193, 1],
 [0.31622776601683794, 1],
 [0.346410161513776, 1],
 [0.5099019513592794, 1],
 [0.5477225575051662, 1],
 [0.5830951894845308, 1],
 [0.6000000000000003, 1],
 [0.6480740698407862, 1],
 [0.6708203932499374, 1],
 [0.6782329983125268, 2],
 [0.7000000000000004, 2],
 [0.7141428428542852, 2],
 [0.7810249675906655, 2],
 [0.7810249675906658, 2],
 [0.787400787401181, 2],
 [0.8246211251235317, 2],
 [0.8246211251235325, 2],
 [0.830662386291808, 1],
 [0.8366600265340753, 2],
 [0.8485281374238575, 1],
 [0.8544003745317528, 2],
 [0.8544003745317538, 1],
 [0.8602325267042625, 2],
 [0.8602325267042633, 2],
 [0.8660254037844396, 1],
 [0.8831760866327845, 2],
 [0.9273618495495711, 1],
 [0.9433981132056607, 2],
 [0.9591663046625434, 2],
 [0.9591663046625444, 2],
 [0.964365076099296, 1],
 [0.9899494936611664, 2],
 [1.0049875621120894, 1],
 [1.0099504938362078, 1],
 [1.0295630140986995, 2],
 [1.0344080432788605, 1],
 [1.0392304845413263, 2],
 [1

In [ ]:
nearest_neighbour_k = 7


In [ ]:
identify = [0 for i in range(len(unique_list))]
for i in range(nearest_neighbour_k):
    identify[distance[i][1]]+=1
print(identify)

[0, 7, 0]


In [ ]:
unique_list

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

In [ ]:
print("Predicted Class is : ",unique_list[identify.index(max(identify))])

Predicted Class is :  Iris-versicolor


In [ ]:
#To find the confusion matrix
#Step1 : Randomize the data (jumbled)
#take 125  vlaues in training and 25 as testing
#you make the confusion matrix (between predicted and original classes)
#find parameters of that confusion matrix

In [ ]:
#To randomize the data 
random_dataset = dataset.sample(frac=1)

In [ ]:
#Seperating the Training and the testing Data For the Featues
train_data_features = random_dataset.values[:125,0:4]
test_data_features = random_dataset.values[125:,0:4]
print(train_data_features)
print("\n\n\n")
print(test_data_features)

[[6.4 3.2 4.5 1.5]
 [6.9 3.2 5.7 2.3]
 [5.5 3.5 1.3 0.2]
 [7.6 3.0 6.6 2.1]
 [4.4 3.0 1.3 0.2]
 [7.7 2.6 6.9 2.3]
 [7.7 2.8 6.7 2.0]
 [6.7 3.1 5.6 2.4]
 [4.4 2.9 1.4 0.2]
 [6.3 2.5 5.0 1.9]
 [7.4 2.8 6.1 1.9]
 [5.1 3.8 1.9 0.4]
 [6.7 2.5 5.8 1.8]
 [7.3 2.9 6.3 1.8]
 [5.1 3.7 1.5 0.4]
 [4.6 3.1 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [5.4 3.9 1.7 0.4]
 [6.4 2.8 5.6 2.1]
 [4.8 3.4 1.6 0.2]
 [6.0 2.7 5.1 1.6]
 [5.7 2.6 3.5 1.0]
 [4.8 3.0 1.4 0.3]
 [6.1 3.0 4.6 1.4]
 [4.7 3.2 1.3 0.2]
 [5.1 3.3 1.7 0.5]
 [6.7 3.3 5.7 2.1]
 [5.6 2.5 3.9 1.1]
 [4.6 3.2 1.4 0.2]
 [5.2 2.7 3.9 1.4]
 [5.5 2.6 4.4 1.2]
 [4.9 3.0 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [6.0 3.0 4.8 1.8]
 [6.7 3.3 5.7 2.5]
 [5.6 3.0 4.5 1.5]
 [5.0 2.0 3.5 1.0]
 [6.3 2.7 4.9 1.8]
 [5.6 2.9 3.6 1.3]
 [7.7 3.8 6.7 2.2]
 [4.8 3.0 1.4 0.1]
 [5.9 3.0 5.1 1.8]
 [5.8 2.7 5.1 1.9]
 [6.4 2.9 4.3 1.3]
 [5.5 2.3 4.0 1.3]
 [6.9 3.1 5.4 2.1]
 [6.0 2.2 5.0 1.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.4 1.9 0.2]
 [5.7 3.0 4.2 1.2]
 [6.3 2.9 5.6 1.8]
 [5.1 3.8 1.5 0.3]
 [6.7 3.0 5.

In [ ]:
train_data_output = random_dataset.values[:125,-1]
test_data_output = random_dataset.values[125:,-1]

print(train_data_output)
print("\n\n\n")
print(test_data_output)

['Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-

In [ ]:

#To find the unique classes from the dataser For the Training Data
unique_list_training = []
for x in train_data_output:
    if x not in unique_list_training:
        unique_list_training.append(x)
print(unique_list)

#to replcae the class with  numerical value
for i in range(len(train_data_output)):
    for k in range(len(unique_list_training)):
        if(train_data_output[i]==unique_list_training[k]):
            train_data_output[i]=k
            break
print(train_data_output)


['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
[0 1 2 1 2 1 1 1 2 1 1 2 1 1 2 2 2 2 1 2 0 0 2 0 2 2 1 0 2 0 0 2 2 1 1 0 0
 1 0 1 2 1 1 0 0 1 1 0 2 0 1 2 0 1 0 2 0 2 1 0 2 0 1 0 1 2 2 0 0 1 1 2 1 2
 0 0 2 1 2 0 0 1 0 0 2 0 0 0 0 2 2 1 1 0 0 2 2 0 1 2 0 2 0 1 0 2 2 1 1 2 1
 2 1 0 2 0 2 1 2 0 2 2 0 2 0]


In [ ]:
#To find the unique classes from the dataser For the Testing Data
unique_list_testing = []
for x in test_data_output:
    if x not in unique_list_testing:
        unique_list_testing.append(x)
print(unique_list_testing)

#to replcae the class with  numerical value
for i in range(len(test_data_output)):
    for k in range(len(unique_list_testing)):
        if(test_data_output[i]==unique_list_testing[k]):
            test_data_output[i]=k
            break
print(test_data_output)


['Iris-setosa', 'Iris-virginica', 'Iris-versicolor']
[0 1 1 1 2 1 0 0 2 1 1 2 0 2 1 2 1 1 1 1 1 0 0 2 2]


In [ ]:
print(metrics.confusion_matrix)